### ISSUE TITLE
Heading of M3 is too big on mobile

### ISSUE THREAD

**Issue by blfpd** [KTibow/ktibow.github.io#23]
Here a screenshot on Firefox mobile on a smallish device (Zenfone 8):

![Screenshot_20241223-184810823.jpg](https://github.com/user-attachments/assets/853a1135-16d3-40ec-b874-61ed18f15de1)

It clashes a bit with the promise of robustness as the title leak out of its container :-/

Your doing a great job and I enjoy that a solid implementation of M3 exists for Svelte 😊

**Comment by KTibow** [comment]
fixed in https://github.com/KTibow/m3-svelte/commit/c98726d0af28515ef9b8800635595c30e47b4690 i think
